### ISSUE TITLE
Typing Issues in v3

### ISSUE THREAD

**Issue by marc-at-brightnight** [jsforce/jsforce#1668]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `jsforce@3.6.6` for the project I'm working on.

I had the following typing issues after upgrading from v1 to v3:
```
Checked 108 files in 17ms. No fixes applied.
../../node_modules/jsforce/src/api/bulk.ts:7:25 - error TS7016: Could not find a declaration file for module 'multistream'. '/Users/marchermann/dev/poweralpha-app/node_modules/multistream/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/multistream` if it exists or add a new declaration (.d.ts) file containing `declare module 'multistream';`

7 import joinStreams from 'multistream';
                          ~~~~~~~~~~~~~

../../node_modules/jsforce/src/http-api.ts:5:20 - error TS7016: Could not find a declaration file for module 'xml2js'. '/Users/marchermann/dev/poweralpha-app/node_modules/xml2js/lib/xml2js.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/xml2js` if it exists or add a new declaration (.d.ts) file containing `declare module 'xml2js';`

5 import xml2js from 'xml2js';
                     ~~~~~~~~

../../node_modules/jsforce/src/soap.ts:74:17 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'SoapSchemaDef | { [key: string]: any; }'.
  No index signature with a parameter of type 'string' was found on type 'SoapSchemaDef | { [key: string]: any; }'.

74       const s = schema_[k];
                   ~~~~~~~~~~


Found 3 errors in 3 files.
```

I added `multistream` and `xml2js` to my dev dependencies to fix problems 1 and 2.

Then I get the following, in addition to problem 3:
```
../../node_modules/jsforce/src/api/bulk.ts:912:5 - error TS2348: Value of type 'typeof MultiStream' is not callable. Did you mean to include 'new'?

912     joinStreams(streams).pipe(dataStream);
        ~~~~~~~~~~~~~~~~~~~~
```

I then patched the package with the following, with the hope this will be fixed soon:

```diff
diff --git a/node_modules/jsforce/src/api/bulk.ts b/node_modules/jsforce/src/api/bulk.ts
index 48b7633..7127dad 100644
--- a/node_modules/jsforce/src/api/bulk.ts
+++ b/node_modules/jsforce/src/api/bulk.ts
@@ -909,6 +909,7 @@ export class Bulk<S extends Schema> {
     const streams = results.map((result) =>
       this.job(result.jobId).batch(result.batchId).result(result.id).stream(),
     );
+    // @ts-expect-error hopefully they will fix this
     joinStreams(streams).pipe(dataStream);
 
     return recordStream;
diff --git a/node_modules/jsforce/src/soap.ts b/node_modules/jsforce/src/soap.ts
index 7230122..1f075df 100644
--- a/node_modules/jsforce/src/soap.ts
+++ b/node_modules/jsforce/src/soap.ts
@@ -71,6 +71,7 @@ export function castTypeUsingSchema(
     }
     const obj = isMapObject(value) ? value : {};
     return Object.keys(schema_).reduce((o, k) => {
+      // @ts-expect-error hopefully they will fix this
       const s = schema_[k];
       const v = obj[k];
       const nillable =
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by marc-at-brightnight** [comment]
Actually just got like 30 more errors, across 9 files. Not sure why these didn't pop up before, although I have made some adjustments to tsconfig and upgrade to latest TS.

They are all similar to...
```
../../node_modules/jsforce/src/util/stream.ts:31:3 - error TS4114: This member must have an 'override' modifier because it overrides a member in the base class 'Writable'.

31   _writev(
     ~~~~~~~

../../node_modules/jsforce/src/util/stream.ts:39:3 - error TS4114: This member must have an 'override' modifier because it overrides a member in the base class 'Writable'.

39   toString(encoding: BufferEncoding = 'utf-8') {
     ~~~~~~~~

../../node_modules/jsforce/src/util/stream.ts:87:3 - error TS4114: This member must have an 'override' modifier because it overrides a member in the base class 'Duplex'.

87   _write(chunk: any, encoding: any, callback: any) {
     ~~~~~~

../../node_modules/jsforce/src/util/stream.ts:91:3 - error TS4114: This member must have an 'override' modifier because it overrides a member in the base class 'Duplex'.

91   _read(n: number) {
```

Typescript 5.8.2, tsconfig below:
```
{
  "incremental": false,
  "target": "esnext",
  "useDefineForClassFields": true,
  "moduleDetection": "force",
  "module": "esnext",
  "moduleResolution": "bundler",
  "baseUrl": "./packages",
  "paths": {
    "@poweralpha/*": [
      "*/src"
    ]
  },
  "allowImportingTsExtensions": false,
  "resolvePackageJsonExports": true,
  "resolvePackageJsonImports": true,
  "resolveJsonModule": true,
  "allowJs": true,
  "declaration": false,
  "declarationMap": false,
  "sourceMap": true,
  "newLine": "lf",
  "preserveConstEnums": true,
  "isolatedModules": true,
  "verbatimModuleSyntax": false,
  "allowSyntheticDefaultImports": true,
  "esModuleInterop": true,
  "forceConsistentCasingInFileNames": true,
  "noImplicitAny": true,
  "strictNullChecks": true,
  "strictFunctionTypes": true,
  "strictBindCallApply": true,
  "strictPropertyInitialization": true,
  "noImplicitThis": true,
  "useUnknownInCatchVariables": true,
  "alwaysStrict": true,
  "noUncheckedIndexedAccess": false,
  "noImplicitOverride": true,
  "skipLibCheck": true,
  "charset": "utf8",
  "importsNotUsedAsValues": "remove",
  "jsxFactory": "React.createElement",
  "jsxFragmentFactory": "React.Fragment",
  "jsxImportSource": "react",
  "reactNamespace": "React",
  "pretty": true,
  "strict": true,
  "types": [
    "cypress",
    "@argos-ci/cypress/support",
    "cypress-real-events"
  ],
  "strictBuiltinIteratorReturn": true
}
```

Really don't want to patch all of these, am I missing something?

**Comment by igorien2k** [comment]
Also experiencing the same problem. Is there an accepted solution?
